const femaleNames = [
  "Elizabeth Jones",
  "Roxanne Valdez",
  "Lynn Freeman",
  "Isabel Paul",
  "Chelsea Baker",
  "Kristin Garrett",
  "Paulette Allison",
  "Josefina Poole",
  "Madeline Tran",
  "Darla Lopez",
  "Olivia Ruiz",
  "Fannie Bowen",
  "Brooke Schneider",
  "Shelia Wheeler",
  "Louise Cobb",
  "Genevieve Johnston",
  "Marguerite Rice",
  "Tonya Hayes",
  "Alexandra Ford",
  "Marta Cook",
  "Adrienne Briggs",
  "Harriet Munoz",
  "Marsha Owens",
  "Bobbie Sullivan",
  "Connie Ingram",
  "Angelina Harmon",
  "Jacquelyn Castro",
  "Essie Erickson",
  "Kristi Ball",
  "Krista Moran",
  "Robin Jimenez",
  "Dolores Franklin",
  "Gertrude Parks",
  "Mona Armstrong",
  "Phyllis Clayton",
  "Jeanne Higgins",
  "Essie Eckson",
  "Tina Turner",
  "Dude Lee",
  "Omega Lambda"
];

const maleNames = [
  "Frankie Chandler",
  "Wade Spencer",
  "Keith Hart",
  "Geoffrey Wong",
  "Homer Rogers",
  "Clyde Bass",
  "Allan Buchanan",
  "Leroy Mathis",
  "Kent Russell",
  "Corey Leonard",
  "Lucas Hodges",
  "Ronald Morrison",
  "Gene Williams",
  "Roderick Hudson",
  "Nicolas Schwartz",
  "Luther Mcdaniel",
  "Jay Ramos",
  "Barry Silva",
  "Sam Fernandez",
  "Carroll Fowler",
  "Troy Jensen",
  "Earl Hayes",
  "Daryl Stevenson",
  "Frank Gibson",
  "Jason Morgan",
  "Marty Young",
  "Alan Henderson",
  "Jesse Zimmerman",
  "Mario Phelps",
  "Preston Singleton",
  "Horace Glover",
  "Claude Stokes",
  "Glen Martinez",
  "Ernesto Mendez",
  "Lynn Stevens",
  "Mathew Taylor",
  "Curtis Griffith",
  "Marlon Snyder",
  "Lloyd Rivera",
  "Edmund George"
]

module.exports = {
  femaleNames,
  maleNames,
}